### ISSUE TITLE
Doubt regarding pre-training of ELECTRA

### ISSUE THREAD

**Issue by saichandrapandraju** [BruceWen120/medal#6]
Hi Bruce,

I liked the idea behind your MeDAL dataset and pre-training concept using abbreviations.

While going through the code, I am not understanding following things. 

1. How are you making the model predict the full form of the abbreviation in a sentence ?

2. Also plz explain what does below block of code does..

`abbs = torch.stack([sents[n, idx, :] for n, idx in enumerate(locs)])  # (B * M)`

**Comment by BruceWen120** [comment]
Thanks for your interest.

1. As explained in the paper, it's casted as a multi-class classification problem, so what we do is we take the representation at the abbreviation's location, and compute the probabilities of each full term.
2. That line of code essentially extracts the representations of abbreviations in all the sentences in the batch. Here B is the batch size and M is the hidden dimension.
